version: '3'
services:
  nodejs:
    image: node
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - nodejs
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql_data:/var/lib/mysql
  web:
    image: nginx:alpine
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - app
volumes:
  mysql_data:
